# Generated by Django 4.2.13 on 2024-10-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0082_subscriber"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriber",
            name="subscribed",
        ),
        migrations.AddField(
            model_name="subscriber",
            name="subscription_class",
            field=models.CharField(
                choices=[("gold", "Gold"), ("silver", "Silver"), ("basic", "Basic")],
                default="basic",
                max_length=6,
            ),
        ),
    ]